### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cvionis** [cvionis/wifi-keys#2]
- [x] Implement error handling (specifically to ensure deletion of profile info files if an error is encountered when script is run)
- [ ] Refactor code into functions to improve readability 
- [ ] Use file.readlines() rather than file.read().split("\n")
- [x] Replace use of os.system() module with subprocess
